# Generated by Django 6.0.4 on 2026-05-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="token",
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="Token"),
        ),
    ]
