# Generated by Django 6.0.4 on 2026-05-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="token",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Token"),
        ),
    ]
