# Generated by Django 6.0.4 on 2026-05-25 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clients",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.CharField(max_length=50, unique=True, verbose_name="Электронная почта")),
                ("name", models.CharField(max_length=100, verbose_name="ФИО")),
                ("comment", models.TextField(blank=True, null=True, verbose_name="Комментарий")),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
                "db_table": "clients",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("theme", models.CharField(max_length=100, verbose_name="Тема письма")),
                ("text", models.TextField(blank=True, null=True, verbose_name="Текст письма")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "db_table": "message",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Distribution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_time", models.DateTimeField(verbose_name="Дата и время первой отправки")),
                ("end_time", models.DateTimeField(verbose_name="Дата и время окончания отправки")),
                (
                    "status",
                    models.CharField(
                        choices=[("finished", "Завершена"), ("create", "Создана"), ("progress", "Запущена")],
                        default="Создана",
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                ("recipients", models.ManyToManyField(related_name="distribution", to="service.clients")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="distribution", to="service.message"
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "db_table": "distribution",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Attemp",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attemp_date", models.DateTimeField(blank=True, null=True, verbose_name="Дата и время попытки")),
                (
                    "status_2",
                    models.CharField(
                        choices=[("success", "Успешно"), ("unsuccess", "Не успешно")],
                        default="Успешно",
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                ("answer_server", models.TextField(blank=True, null=True, verbose_name="Ответ почтового сервера")),
                (
                    "distribution_message_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribution_message_2",
                        to="service.distribution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка",
                "verbose_name_plural": "Попытки",
                "db_table": "attemp",
                "ordering": ["id"],
            },
        ),
    ]
