# Generated by Django 6.0.4 on 2026-05-25 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attemp",
            old_name="attemp_date",
            new_name="attempt_time",
        ),
        migrations.RenameField(
            model_name="attemp",
            old_name="answer_server",
            new_name="server_response",
        ),
        migrations.RemoveField(
            model_name="attemp",
            name="distribution_message_2",
        ),
        migrations.AddField(
            model_name="attemp",
            name="mailing",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailing",
                to="service.distribution",
            ),
            preserve_default=False,
        ),
    ]
