# Generated by Django 6.0.4 on 2026-05-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_rename_attemp_date_attemp_attempt_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attemp",
            name="count_emails",
            field=models.PositiveIntegerField(default=1, verbose_name="Количество получателей"),
        ),
    ]
