# Generated by Django 6.0.4 on 2026-05-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0004_attemp_owner_clients_owner_distribution_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distribution",
            name="status",
            field=models.CharField(
                choices=[
                    ("finished", "Завершена"),
                    ("create", "Создана"),
                    ("progress", "Запущена"),
                    ("paused", "Приостановлена"),
                ],
                default="Создана",
                max_length=30,
                verbose_name="Статус",
            ),
        ),
    ]
